repos:
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.15.2
  hooks:
  - id: gitleaks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
    - id: end-of-file-fixer
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.14.2
  hooks:
    - id: helm-docs
      args:
        - --chart-search-root=charts
        - --template-files=./_templates.gotmpl
        - --template-files=README.md.gotmpl
