image:
  repository: ghcr.io/hartmanfrost/enshrouded-server
  tag: proton-v2.1.5
  ceserverTag: ceserver-v2.1.5

service:
  type: LoadBalancer
  externalIPs: []
  annotations: {}

resources:
  requests:
    memory: 6G
    cpu: 4.0

volumes:
  dataPVC:
    # -- Size of the persistent volume for gamedata
    size: 30Gi
    storageClassName: ""
  savegamePVC:
    # -- Size of the persistent volume for savegames
    size: 10Gi
    storageClassName: ""

config:
  # -- Server name
  serverName: "Enshrouded Server"
  # -- Server IP
  serverIP: "127.0.0.1"
  # -- Server password. If not set, password will be generated randomly.
  userPassword: ""
  # -- Admin password. If not set, password will be generated randomly.
  adminPassword: ""
  # -- Existing secret name for server password. Must contain key named "password". If set `serverPassword` will be ignored.
  serverPasswordExistingSecretName: ""
  gamePort: 15636
  queryPort: 15637
  # -- Number of server slots
  serverSlots: 16
