{{- if not .Values.config.serverPasswordExistingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "enshrouded.passwordSecretName" .}}
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  userPassword:  {{ .Values.config.userPassword  | default (randAlphaNum 10) | quote }}
  adminPassword: {{ .Values.config.adminPassword | default (randAlphaNum 10) | quote }}
{{- end }}
